// JavaScript Document for manage languages

// Deutsch
var labels_de = {
	// Months
	month1: "Jan",
	month2: "Feb",
	month3: "Mar",
	month4: "Apr",
	month5: "Mai",
	month6: "Jun",
	month7: "Jul",
	month8: "Aug",
	month9: "Sep",
	month10: "Okt",
	month11: "Nov",
	month12: "Dec",
	
	// Footer Labels
	legalNotices_text: "Rechtlicher Hinweis",
	legalNotices_title: "Haftungsausschluss und Copyright-Vermerk",
	dataProtection_text: "Datenschutzn",
	dataProtection_title: "Pers&ouml;nliche Datenschutzerkl&auml;rung",
	compatibility_text: "Kompatibilit&auml;t",
	compatibility_title: "Kompatibilit&auml;t",
	compatibility_src: "http://oami.europa.eu/ows/rw/pages/compatibility.de.do",
	version: "Version",
	organization: "Harmonisierungsamt f&uuml;r den Binnenmarkt (Marken, Muster und Modelle)",
	address: "Avenida de Europa 4, E-03008 Alicante, Spain - Tel: +34 96 513 9400 - e-mail",
	
	// Header Labels
	helpFiles_text: "FAQ",
	helpFiles_title: "H&auml;ufig gestellte Fragen)",
	helpFiles_src: "",
	contact_text: "Kontakte",
	contact_title: "Kontaktieren Sie uns",
	siteMap_text: "Sitemap",
	siteMap_title: "Sitemap",
	links_text: "Links",
	links_title: "Links",
	title_text: "HABM",
	title_title: "Harmonisierungsamt f&uml;r den Binnenmarkt",
	description: "Das Amt der Europ&auml;ischen Union f&uuml;r die Eintragung von Marken und Geschmacksmustern",
	HOMELabel_text: "Home",
	HOMELabel_title: "Hauptseite",
	CTMLabel_text: "Marken",
	CTMLabel_title: "Die Gemeinschaftsmarke",
	RCDLabel_text: "Geschmacksmuster",
	RCDLabel_title: "Das Gemeinschaftsgeschmacksmuster",
	YOULabel_text: "Qualit&auml;t plus",
	YOULabel_title: "Qualit&auml;t plus",
	ABOUTLabel_text: "&Uuml;ber das HABM",
	ABOUTLabel_title: "&Uuml;ber das HABM",
	breadcrumb: "Sie befinden sich hier",
	languages_title: "Tastaturbenutzer: Dr&uuml;cken Sie ALT+Pfeil nach unten, um das Dropdown-Men&uuml; mit den Sprachoptionen  zu &ouml;ffnen. Dr&uuml;cken Sie OK, um Ihre Wahl zu treffen.",
	
	// CTM Menu
	CTMTitle: "Marken",
	CTMWhatIs: "Was ist eine Marke?",
	CTMWhatIsCommunity: "Was ist eine Gemeinschaftsmarke?",
	CTMExtending: "Ausweitung des Schutzes einer GM au&szlig;erhalb der EU",
	CTMTheCTM: "Die Gemeinschaftsmarke",
	CTMInternationalRegistrations: "Internationale Registrierungen, in denen die EG benannt ist",
	CTMInternationalMark: "Die GM im Vergleich zur internationalen Marke",
	CTMPublication: "Ver&ouml;ffentlichung",
	CTMSearches: "Recherchen",
	CTMOpposition: "Widerspruch",
	CTMRegistration: "Eintragung",
	CTMInvalidity: "Nichtigkeit und Verfall",
	CTMFeesPayments: "Geb&uuml;hren und Zahlungsmodalit&auml;ten",
	CTMBulletin: "Blatt f&uuml;r Gemeinschaftsmarken",
	CTMNotifications: "&Ouml;ffentliche Zustellungen",
	CTMJudgements: "Urteile der Gemeinschaftsmarkengerichte",
	CTMManual: "Handbuch des HABM zur aktuellen Gemeinschaftsmarkenpraxis",
	
	// RCD Menu
	RCDTitle: "Geschmacksmuster",
	RCDWhatIs: "Was ist ein Geschmacksmuster?",
	RCDWhatIsCommunity: "Was ist ein Gemeinschaftsgeschmacksmuster?",
	RCDRegisteredRCD: "Das eingetragenen Gemeinschaftsgeschmacksmuster",
	RCDInternationalRegistrations: "Internationale Eintragungen",
	RCDUnregistered: "Das nicht eingetragene Gemeinschaftsgeschmacksmuster",
	RCDRegistrationPublication: "Registration and publication",
	RCDInvalidity: "Invalidity",
	RCDFeesPayment: "Geb&uuml;hren und Zahlungsmodalit&auml;ten",
	RCDBulletin: "Blatt f&uuml;r Gemeinschaftsgeschmacksmuster",
	RCDNotifications: "&Ouml;ffentliche Zustellungen",
	RCDInvalidityDecisions: "Entscheidungen der Nichtigkeitsabteilung / anh&auml;ngige Verfahren",
	RCDBoards: "Entscheidungen der Beschwerdekammern",
	RCDJudgementsCourt: "Urteile des Europ&auml;ischen Gerichtshofes",
	RCDJudgements: "Urteile der Gemeinschaftsgeschmacksmuster-gerichte",
	
	// YOU Menu
	YOUTitle: "Qualit&auml;t plus",
	YOUQuality: "Qualit&auml;tsmanagementsystem",
	YOUService: "Dienstleistungscharta",
	YOUSatisfaction: "Umfrage zur Nutzerzufriedenheit",
	YOUComplaints: "Dienststelle f&uuml;r Kundenbeschwerden",
	YOUCooperationProjects: "Technische Kooperationsvereinbarungen mit den nationalen Ämtern",
	YOUNetworks: "Netzwerke und Nutzergruppen",
	YOUOffices: "Nationale &Auml;mter",
	YOUOAMIGroup: "Nutzergruppe des HABM",
	YOUEBusinessGroup: "E-Business Nutzergruppe",
	YOUEuropeanJudges: "Europ&auml;isches Richtersymposium",
	YOUCooperation: "Kooperation mit den USA und Japan",
	YOUOHIMNetwork: "Universit&auml;tennetzwerk des HABM",
	YOULinks: "Links",
	YOUMyPage: "MyPage",
	YOUDatabases: "Datenbanken",
	YOUSearchCTM: "Suche nach einer Gemeinschaftsmarke",
	YOUSearchRCD: "Suche nach einem Gemeinschaftsgeschmacksmuster",
	YOUSearchEuronice: "Klassifizierungssuchmaschine f&uuml;r Marken - EURONICE/EUROACE",
	YOUSearchEurolocarno: "Klassifizierungssuchmaschine f&uuml;r Geschmacksmuster - EUROLOCARNO",
	YOUFindRep: "Suche nach einem Vertreter - FindRep",
	YOUEuroclass: "EuroClass",
	YOUFormsFilings: "Formulare",
	YOUOnlineFiling: "Elektronische Formulare",
	YOUFileCTM: "Anmeldung einer Gemeinschaftsmarke",
	YOUFileRCD: "Anmeldung eines Gemeinschaftsgeschmacksmusters",
	YOURenewCTM: "Verl&auml;ngerung einer Gemeinschaftsmarke",
	YOURenewRCD: "Verl&auml;ngerung eines Gemeinschaftsgeschmacksmusters",
	YOUFileOpposition: "Erhebung eines Widerspruchs",
	YOUDownloadable: "Nicht elektronische Formulare",
	
	// ABOUT Menu
	ABOUTTitle: "Über das HABM",
	ABOUTContact: "Kontaktieren Sie uns",
	ABOUTInstitutionalInformation: "Institutionelle Informationen",
	ABOUTWelcome: "Gru&szlig;wort des Pr&auml;sidenten",
	ABOUTAdministrative: "Verwaltungsrat und Haushaltsausschuss",
	ABOUTFinance: "Finanzen",
	ABOUTChart: "Organigramm",
	ABOUTAppeal: "Beschwerdekammern",
	ABOUTEnlargement: "Erweiterung",
	ABOUTRequesting: "Beantragung von Verwaltungsdokumenten",
	ABOUTStatistics: "Statistiken",
	ABOUTPublications: "Ver&ouml;ffentlichungen des HABM",
	ABOUTNewsEvents: "Neuigkeiten und Veranstaltungen",
	ABOUTNews: "Neuigkeiten",
	ABOUTEvents: "Veranstaltungen",
	ABOUTMultimedia: "Multimedia",
	ABOUTCorporate: "HABM Corporate",
	ABOUTEBusiness: "HABM E-Business",
	ABOUTCareer: "Stellenangebote und Praktika",
	ABOUTProcurement: "&Ouml;ffentliches Vergabeverfahren",
	ABOUTRunning: "Laufende Offenes Verfahren",
	ABOUTOtherRunning: "Andere Laufende Verfahren",
	ABOUTClosed: "Geschlossene Verfahren",
	ABOUTUseful: "N&uuml;tzliche Dokumente und verschiedene Informationen",
	ABOUTEnvironment: "Umwelt",
	
	// Menu FAQ
	FAQ: "H&auml;ufig gestellte Fragen",
	FAQ1: "1. Allgemeine Fragen",
	FAQ2_CTM: "2. Anmeldeverfahren",
	FAQ2_RCD: "2. Anmeldungen von eingetragener Gemeinschaftsgeschmacksmuster",
	FAQ3_CTM: "3. Geb&uuml;hren und Zahlungsmodalit&auml;ten",
	FAQ3_RCD: "3. Geb&uuml;hren",
	FAQ4_CTM: "4. Vertretung vor dem HABM",
	FAQ4_RCD: "4. Vertretung vor dem Amt",
	FAQ5_CTM: "5. Das GM-Eintragungsverfahren",
	FAQ5_RCD: "5. Verfahren",
	FAQ6: "6. Recherche",
	FAQ7_CTM: "7. Das GM-Register",
	FAQ7_RCD: "7. Register",
	FAQ8_CTM: "8. Widerspruch",
	FAQ8_RCD: "8. Nicht eingetragenes Gemeinschaftsgeschmacksmuster",
	FAQ9_CTM: "9. L&ouml;schungsverfahren",
	FAQ9_RCD: "9. Nichtigkeit",
	FAQ10_CTM: "10. Beschwerde",
	FAQ12_RCD: "10. Erweiterung",
	FAQ11_CTM: "11. Erweiterung",
	FAQ11_RCD: "11. E-Filing (elektronische Anmeldung)",
	FAQ12_CTM: "12. Eintragung von internationalen Marken",
	FAQ12_RCD: "12. H&auml;ufig gestellte Fragen zum Haager Abkommen",
	FAQ13_CTM: "13. E-business",
	FAQ13_RCD: "13. Beschwerde",
	
	// Menu Common
	howToProtection: "Wie Schutz erlangt werden kann",
	registrationProcess: "TDas Eintragungsverfahren",
	filing: "Anmeldung",
	classification: "Klassifizierung",
	examination: "Pr&uuml;fung",
	changes: "&Auml;nderungen im Register",
	appeal: "Beschwerde",
	representation: "Vertretung vor dem Amt",
	inspection: "Inspection of files and copies",
	renewals: "Verl&auml;ngerungen",
	caselaw: "Rechtsprechung",
	legalTexts: "Rechtstexte",
	decisions: "Entscheidungen des Amtes",
	judgementsEuropean: "Urteile des Europ&auml;ischen Gerichtshofes",
	regulations: "Verordnungen und damit in Zusammenhang stehende Texte",
	president: "Beschl&uuml;sse und Mitteilungen des Pr&auml;sidentent",
	guidelines: "Richtlinien",
	presidium: "Beschl&uuml;sse des Pr&auml;sidiums der Beschwerdekammern",
	treaties: "Internationale Vertr&auml;ge",
	enforcement: "Vollstreckung und gewerbliche Eigentumsrechte"

}

// English
var labels_en = {
	// Months
	month1: "Jan",
	month2: "Feb",
	month3: "Mar",
	month4: "Apr",
	month5: "May",
	month6: "Jun",
	month7: "Jul",
	month8: "Aug",
	month9: "Sep",
	month10: "Oct",
	month11: "Nov",
	month12: "Dec",
	
	// Footer Labels
	legalNotices_text: "Legal Notices",
	legalNotices_title: "Disclaimer and Copyright notice",
	dataProtection_text: "Data Protection",
	dataProtection_title: "Personal data protection statement",
	compatibility_text: "Compatibility",
	compatibility_title: "Compatibility",
	compatibility_src: "http://oami.europa.eu/ows/rw/pages/compatibility.en.do",
	version: "Version",
	organization: "Office for Harmonization in the Internal Market (Trade Marks and Designs)",
	address: "Avenida de Europa 4, E-03008 Alicante, Spain - Tel: +34 96 513 9400 - e-mail",
	
	// Header Labels
	helpFiles_text: "FAQ",
	helpFiles_title: "Frequently asked questions",
	helpFiles_src: "",
	contact_text: "Contact us",
	contact_title: "Send us your comments or questions",
	siteMap_text: "Site map",
	siteMap_title: "Site map",
	links_text: "Links",
	links_title: "Links",
	title_text: "OHIM",
	title_title: "Office for Harmonization in the Internal Market",
	description: "The Trade Marks and Designs Registration Office of the European Union",
	HOMELabel_text: "Home",
	HOMELabel_title: "Home page",
	CTMLabel_text: "Trade Marks",
	CTMLabel_title: "The Community Trade Mark",
	RCDLabel_text: "Designs",
	RCDLabel_title: "The Community Design",
	YOULabel_text: "Quality plus",
	YOULabel_title: "Quality Plus",
	ABOUTLabel_text: "About OHIM",
	ABOUTLabel_title: "About OHIM",
	breadcrumb: "You are here",
	languages_title: "Keyboard users: Press ALT+down arrow to open dropdown menu to browse through the language options and then press ENTER to make your selection",
	
	// CTM Menu
	CTMTitle: "Trade Marks",
	CTMWhatIs: "What is a trade mark?",
	CTMWhatIsCommunity: "What is a Community trade mark?",
	CTMExtending: "Extending a CTM outside the EU",
	CTMTheCTM: "The Community trade mark",
	CTMInternationalRegistrations: "International Registrations designating the EC",
	CTMInternationalMark: "CTM vs International Mark",
	CTMPublication: "Publication",
	CTMSearches: "Searches",
	CTMOpposition: "Opposition",
	CTMRegistration: "Registration",
	CTMInvalidity: "Invalidity and revocation",
	CTMFeesPayments: "Fees and payments",
	CTMBulletin: "CTM bulletin",
	CTMNotifications: "Public notifications",
	CTMJudgements: "Judgements of the Community Trade Mark Courts",
	CTMManual: "OHIM manual on current CTM practice",
	
	// RCD Menu
	RCDTitle: "Designs",
	RCDWhatIs: "What is a design?",
	RCDWhatIsCommunity: "What is a Community design?",
	RCDRegisteredRCD: "The registered Community design",
	RCDInternationalRegistrations: "International Registrations",
	RCDUnregistered: "The unregistered Community design",
	RCDRegistrationPublication: "Registration and publication",
	RCDInvalidity: "Invalidity",
	RCDFeesPayment: "Fees and payment",
	RCDBulletin: "RCD bulletin",
	RCDNotifications: "Public notifications",
	RCDInvalidityDecisions: "Invalidity decisions/Pending cases",
	RCDBoards: "Boards of Appeal decisions",
	RCDJudgementsCourt: "Judgements of the European Court of Justice",
	RCDJudgements: "Judgements of the Community Design Courts",
	
	// YOU Menu
	YOUTitle: "Quality plus",
	YOUQuality: "Quality management system",
	YOUService: "Service charter",
	YOUSatisfaction: "User satisfaction survey",
	YOUComplaints: "Complaints unit",
	YOUCooperationProjects: "Technical Cooperation agreements with National offices",
	YOUNetworks: "Networks and Users' Groups",
	YOUOffices: "National Offices",
	YOUOAMIGroup: "OAMI Users' Group",
	YOUEBusinessGroup: "E-Business Users' Group",
	YOUEuropeanJudges: "European Judges Symposium",
	YOUCooperation: "Cooperation with US and Japan",
	YOUOHIMNetwork: "OHIM Universities Network",
	YOULinks: "Links",
	YOUMyPage: "MyPage",
	YOUDatabases: "Databases",
	YOUSearchCTM: "Search a Community trade mark",
	YOUSearchRCD: "Search a Community design",
	YOUSearchEuronice: "Search classification for trade marks - EURONICE/EUROACE",
	YOUSearchEurolocarno: "Search classification for designs - EUROLOCARNO",
	YOUFindRep: "Search for representatives - FindRep",
	YOUEuroclass: "EuroClass",
	YOUFormsFilings: "Forms/Filing",
	YOUOnlineFiling: "Online filing",
	YOUFileCTM: "File a Community trade mark online",
	YOUFileRCD: "File a Community design online",
	YOURenewCTM: "Renew a Community trade mark online",
	YOURenewRCD: "Renew a Community design online",
	YOUFileOpposition: "File an opposition online",
	YOUDownloadable: "Downloadable forms",
	
	// ABOUT Menu
	ABOUTTitle: "About OHIM",
	ABOUTContact: "Contact us",
	ABOUTInstitutionalInformation: "Institutional Information",
	ABOUTWelcome: "Welcome from the President",
	ABOUTAdministrative: "Administrative Board and Budget Comitee",
	ABOUTFinance: "Finance",
	ABOUTChart: "Organisational chart",
	ABOUTAppeal: "Boards of Appeal",
	ABOUTEnlargement: "Enlargement",
	ABOUTRequesting: "Requesting administrative documents",
	ABOUTStatistics: "Statistics",
	ABOUTPublications: "OHIM Publications",
	ABOUTNewsEvents: "News and events",
	ABOUTNews: "News",
	ABOUTEvents: "Events",
	ABOUTMultimedia: "Multimedia",
	ABOUTCorporate: "OHIM Corporate",
	ABOUTEBusiness: "OHIM E-Business",
	ABOUTCareer: "Career opportunities and traineeships",
	ABOUTProcurement: "Public procurement",
	ABOUTRunning: "Running open procedures",
	ABOUTOtherRunning: "Other running procedures",
	ABOUTClosed: "Closed procedures",
	ABOUTUseful: "Useful documents and other information",
	ABOUTEnvironment: "Environment",
	
	// Menu FAQ
	FAQ: "FAQ",
	FAQ1: "1. General Questions",
	FAQ2_CTM: "2. Application Procedure",
	FAQ2_RCD: "2. Registered Community design applications",
	FAQ3_CTM: "3. Fees and their Payment",
	FAQ3_RCD: "3. Fees",
	FAQ4_CTM: "4. Representation before OHIM",
	FAQ4_RCD: "4. Representation before the office",
	FAQ5_CTM: "5. The CTM Registration procedure",
	FAQ5_RCD: "5. Procedure",
	FAQ6: "6. Search",
	FAQ7_CTM: "7. The CTM Register",
	FAQ7_RCD: "7. Register",
	FAQ8_CTM: "8. Opposition",
	FAQ8_RCD: "8. Unregistered community design",
	FAQ9_CTM: "9. Cancellation proceedings",
	FAQ9_RCD: "9. Invalidity",
	FAQ10_CTM: "10. Appeal",
	FAQ12_RCD: "10. Enlargement",
	FAQ11_CTM: "11. Enlargement",
	FAQ11_RCD: "11. E-Filing",
	FAQ12_CTM: "12. Registration of International Marks",
	FAQ12_RCD: "12. FAQ on the Hague Agreement",
	FAQ13_CTM: "13. E-business",
	FAQ13_RCD: "13. Appeal",
	
	// Menu Common
	howToProtection: "How to obtain protection",
	registrationProcess: "The registration process",
	filing: "Filing",
	classification: "Classification",
	examination: "Examination",
	changes: "Changes to the Register",
	appeal: "Appeal",
	representation: "Representation before the Office",
	inspection: "Inspection of files and copies",
	renewals: "Renewals",
	caselaw: "Case-law",
	legalTexts: "Legal texts",
	decisions: "Decisions of the Office",
	judgementsEuropean: "Judgements of the European Court of Justice",
	regulations: "Regulations and related texts",
	president: "Decisions and Communications of the President",
	guidelines: "Guidelines",
	presidium: "Decisions of the Presidium of the Boards of Appeal",
	treaties: "International treaties",
	enforcement: "Enforcement and IP rights"

}

// Español
var labels_es = {
	// Months
	month1: "Ene",
	month2: "Feb",
	month3: "Mar",
	month4: "Abr",
	month5: "May",
	month6: "Jun",
	month7: "Jul",
	month8: "Ago",
	month9: "Sep",
	month10: "Oct",
	month11: "Nov",
	month12: "Dic",
	
	// Footer Labels
	legalNotices_text: "Aviso legal",
	legalNotices_title: "Disclaimer y nota sobre derechos de autor",
	dataProtection_text: "Protecci&oacute;n de datos",
	dataProtection_title: "Declaraci&oacute;n sobre protecci&oacute;n de datos personales",
	compatibility_text: "Compatibilidad",
	compatibility_title: "Compatibilidad",
	compatibility_src: "http://oami.europa.eu/ows/rw/pages/compatibility.es.do",
	version: "Versi&oacute;n",
	organization: "Oficina de Armonizaci&oacute;n del Mercado Interior (Marcas, Dibujos y Modelos)",
	address: "Avenida de Europa 4, E-03008 Alicante, Espa&ntilde;a - Tel: +34 96 513 9400 - e-mail",
	
	// Header Labels
	helpFiles_text: "FAQ",
	helpFiles_title: "Preguntas m&aacute;s frecuentes",
	helpFiles_src: "",
	contact_text: "Contacto",
	contact_title: "Contacte con nosotros",
	siteMap_text: "Plano del sitio",
	siteMap_title: "Mapa del sitio",
	links_text: "Enlaces",
	links_title: "Enlaces",
	title_text: "OAMI",
	title_title: "Oficina para la Armonizaci&oacute;n del Mercado Interior",
	description: "La Oficina de Registro de las Marcas, Dibujos y Modelos de la Uni&oacute;n Europea",
	HOMELabel_text: "Inicio",
	HOMELabel_title: "P&aacute;gina de inicio",
	CTMLabel_text: "Marcas",
	CTMLabel_title: "La Marca Comunitaria",
	RCDLabel_text: "Dibujos y modelos",
	RCDLabel_title: "El dibujo y el modelo comunitario",
	YOULabel_text: "Calidad plus",
	YOULabel_title: "Calidad plus",
	ABOUTLabel_text: "Acerca de la OAMI",
	ABOUTLabel_title: "Acerca de la OAMI",
	breadcrumb: "Se encuentra usted aqu&iacute;",
	languages_title: "Usuarios del teclado: Pulsar ALT+flecha abajo para abrir el men&uacute; desplegable y recorrer las opciones de las lenguas y, a continuaci&oacute;n, pulsar ENTER para confirmar la selecci&oacute;n",
	
	// CTM Menu
	CTMTitle: "Marcas",
	CTMWhatIs: "&iquest;Qu&eacute; es una marca?",
	CTMWhatIsCommunity: "&iquest;Qu&eacute; es una marca comunitaria?",
	CTMExtending: "Extensi&oacute;n de una MC fuera de la UE",
	CTMTheCTM: "La marca comunitaria",
	CTMInternationalRegistrations: "Registros internacionales que designan a la CE",
	CTMInternationalMark: "La marca comunitaria frente a la marca internacional",
	CTMPublication: "Publicaci&oacute;n",
	CTMSearches: "B&uacute;squedas",
	CTMOpposition: "Oposici&oacute;n",
	CTMRegistration: "Registro",
	CTMInvalidity: "Nulidad y caducidad",
	CTMFeesPayments: "Tasas y pagos",
	CTMBulletin: "Bolet&iacute;n de Marcas Comunitarias",
	CTMNotifications: "Notificaciones p&uacute;blicas",
	CTMJudgements: "Sentencias del Tribunal de Justicia de las Comunidades Europeas",
	CTMManual: "Manual pr&aacute;ctico de la OAMI en materia de marcas",
	
	// RCD Menu
	RCDTitle: "Dibujos y Modelos",
	RCDWhatIs: "&iquest;Qu&eacute; es un dibujo o modelo?",
	RCDWhatIsCommunity: "&iquest;Qu&eacute; es un dibujo o modelo comunitario?",
	RCDRegisteredRCD: "Los dibujos y modelos comunitarios registrados",
	RCDInternationalRegistrations: "Los registros internationales",
	RCDUnregistered: "Los dibujos y modelos comunitarios no registrados",
	RCDRegistrationPublication: "Registro y publicaci&oacute;n",
	RCDInvalidity: "Nulidad",
	RCDFeesPayment: "Tasas y pagos",
	RCDBulletin: "Bolet&iacute;n de Dibujos y Modelos Comunitarios",
	RCDNotifications: "Notificaciones p&uacute;blicas",
	RCDInvalidityDecisions: "Resoluciones de nulidad/Asuntos pendientes",
	RCDBoards: "Resoluciones de las Salas de Recurso",
	RCDJudgementsCourt: "Sentencias del Tribunal de Justicia de las Comunidades Europeas",
	RCDJudgements: "Resoluciones de los Tribunales de Dibujos y Modelos Comunitarios",
	
	// YOU Menu
	YOUTitle: "Calidad plus",
	YOUQuality: "Sistema de gesti&oacute;n de calidad",
	YOUService: "Estatuto de Servicio",
	YOUSatisfaction: "Estudio de Satisfacci&oacute;n de los Usuarios",
	YOUComplaints: "Unidad de Quejas",
	YOUCooperationProjects: "Acuerdos de cooperaci&oacute;n t&eacute;cnica con las oficinas nacionales",
	YOUNetworks: "Redes y Grupos de usuarios",
	YOUOffices: "Oficinas nationales",
	YOUOAMIGroup: "Grupo de Usuarios de la OAMI",
	YOUEBusinessGroup: "Grupo de Usuarios de e-Business",
	YOUEuropeanJudges: "Simposio de Jueces Europeos",
	YOUCooperation: "Cooperaci&oacute;n con EEUU y Jap&oacute;n",
	YOUOHIMNetwork: "Red de Universidades de la OAMI",
	YOULinks: "Enlaces",
	YOUMyPage: "MyPage",
	YOUDatabases: "Bases de datos",
	YOUSearchCTM: "B&uacute;squeda de una marca comunitaria",
	YOUSearchRCD: "B&uacute;squeda de un dibujo o modelo comunitario",
	YOUSearchEuronice: "B&uacute;squeda de la clasificaci&oacute;n para marcas comunitarias - EURONICE/EUROACE",
	YOUSearchEurolocarno: "B&uacute;squeda de la clasificaci&oacute;n para dibujos y modelos comunitarios - EUROLOCARNO",
	YOUFindRep: "B&uacute;squeda de un agente - FindRep",
	YOUEuroclass: "EuroClass",
	YOUFormsFilings: "Formularios",
	YOUOnlineFiling: "Electr&oacute;nicos",
	YOUFileCTM: "Presentaci&oacute;n de una solicitud de marca comunitaria",
	YOUFileRCD: "Presentaci&oacute;n de una solicitud de dibujo o modelo comunitario",
	YOURenewCTM: "Renovaci&oacute;n de una marca comunitaria",
	YOURenewRCD: "Renovaci&oacute;n de un dibujo o modelo comunitario",
	YOUFileOpposition: "Presentaci&oacute;n de un escrito de oposici&oacute;n",
	YOUDownloadable: "No electr&oacute;nicos",
	
	// ABOUT Menu
	ABOUTTitle: "Acerca de la OAMI",
	ABOUTContact: "Contacte con nosotros",
	ABOUTInstitutionalInformation: "Informaci&oacute;n institucional",
	ABOUTWelcome: "Bienvenida del Presidente",
	ABOUTAdministrative: "Consejo de Administraci&oacute;n y Comit&eacute; Presupuestario",
	ABOUTFinance: "Finanzas",
	ABOUTChart: "Organigrama",
	ABOUTAppeal: "Salas de Recurso",
	ABOUTEnlargement: "Ampliaci&oacute;n",
	ABOUTRequesting: "Petici&oacute;n de documentos administrativos",
	ABOUTStatistics: "Estad&iacute;sticas",
	ABOUTPublications: "Publicaciones de la OAMI",
	ABOUTNewsEvents: "Noticias y eventos",
	ABOUTNews: "Noticias",
	ABOUTEvents: "Eventos",
	ABOUTMultimedia: "Multimedia",
	ABOUTCorporate: "OAMI Corporativa",
	ABOUTEBusiness: "OAMI E-Business",
	ABOUTCareer: "Ofertas de empleo y pr&aacute;cticas",
	ABOUTProcurement: "Contrataci&oacute;n p&uacute;blica",
	ABOUTRunning: "Procedimientos abiertos en curso",
	ABOUTOtherRunning: "Otros procedimientos en curso",
	ABOUTClosed: "Procedimientos cerrados",
	ABOUTUseful: "Documentaci&oacute;n de inter&eacute;s y otras informaciones",
	ABOUTEnvironment: "Entorno",
	
	// Menu FAQ
	FAQ: "Preguntas m&aacute;s frecuentes",
	FAQ1: "1. Preguntas de car&aacute;cter general ",
	FAQ2_CTM: "2. El procedimiento de solicitud ",
	FAQ2_RCD: "2. Las solicitudes de dibujo o modelo comunitario registrado",
	FAQ3_CTM: "3. Las tasas y su pago ",
	FAQ3_RCD: "3. Las tasas",
	FAQ4_CTM: "4. La representaci&oacute;n ante la OAMI",
	FAQ4_RCD: "4. La representaci&oacute;n ante la Oficina",
	FAQ5_CTM: "5. El procedimiento de registro de una MC",
	FAQ5_RCD: "5. El procedimiento",
	FAQ6: "6. La b&uacute;squeda",
	FAQ7_CTM: "7. El Registro de Marcas Comunitarias",
	FAQ7_RCD: "7. El Registro",
	FAQ8_CTM: "8. La oposici&oacute;n",
	FAQ8_RCD: "8. Los dibujos y modelos comunitarios no registrados",
	FAQ9_CTM: "9. El procedimiento de anulaci&oacute;n",
	FAQ9_RCD: "9. La nulidad",
	FAQ10_CTM: "10. El recurso",
	FAQ12_RCD: "10. La ampliaci&oacute;n",
	FAQ11_CTM: "11. La ampliaci&oacute;n",
	FAQ11_RCD: "11. E-Filing",
	FAQ12_CTM: "12. El Registro de Marcas Internacionales",
	FAQ12_RCD: "12. Preguntas m&aacute;s frecuentes sobre el Arreglo de La Haya",
	FAQ13_CTM: "13. El comercio electr&oacute;nico (e-business)",
	FAQ13_RCD: "13. Recurso",
	
	// Menu Common
	howToProtection: "&iquest;C&oacute;mo obtener protecci&oacute;n?",
	registrationProcess: "El proceso de registro",
	filing: "Presentaci&oacute;n de la solicitud",
	classification: "Clasificaciones",
	examination: "Examen",
	changes: "Cambios en el registro",
	appeal: "Recurso",
	representation: "Representation ante la Oficina",
	inspection: "Consulta de expedientes y copias",
	renewals: "Renovaciones",
	caselaw: "Jurisprudencia",
	legalTexts: "Textos jur&iacute;dicos",
	decisions: "Resoluciones de la Oficina",
	judgementsEuropean: "Sentencias del Tribunal de Justicia de las Comunidades Europeas",
	regulations: "Reglamentos y textos relacionados",
	president: "Decisiones y Comunicaciones del Presidente",
	guidelines: "Directrices",
	presidium: "Decisiones del Presidium de las Salas de Recurso",
	treaties: "Tratados internacionales",
	enforcement: "Respeto de los derechos de PI"

}

// Français
var labels_fr = {
	// Months
	month1: "Jan",
	month2: "F&eacute;v",
	month3: "Mar",
	month4: "Avr",
	month5: "Mai",
	month6: "Jui",
	month7: "Jul",
	month8: "Ao&ucirc;",
	month9: "Sep",
	month10: "Oct",
	month11: "Nov",
	month12: "D&eacute;c",
	
	// Footer Labels
	legalNotices_text: "Avis juridique",
	legalNotices_title: "Clause de non responsabilit&eacute; et droit de reproduction",
	dataProtection_text: "Protection des donn&eacute;es",
	dataProtection_title: "D&eacute;claration de protection des donn&eacute;es &agrave; caract&egrave;re personnel",
	compatibility_text: "Compatibilit&eacute;",
	compatibility_title: "Compatibilit&eacute;",
	compatibility_src: "http://oami.europa.eu/ows/rw/pages/compatibility.fr.do",
	version: "Version",
	organization: "Office de l'harmonisation dans le march&eacute; int&eacute;rieur (marques, dessins et mod&egrave;les)",
	address: "Avenida de Europa 4, E-03008 Alicante, Espagne - T&eacute;l: +34 96 513 9400 - e-mail",
	
	// Header Labels
	helpFiles_text: "FAQ",
	helpFiles_title: "Questions courantes",
	helpFiles_src: "",
	contact_text: "Contacter",
	contact_title: "Contactez-nous",
	siteMap_text: "Carte du site",
	siteMap_title: "Carte du site",
	links_text: "Liens",
	links_title: "Liens",
	title_text: "OHMI",
	title_title: "OHMI",
	description: "L'Office d'Enregistrement des Marques et des Dessins ou Mod&egrave;les de L'Union Europ&eacute;enne",
	HOMELabel_text: "Accueil",
	HOMELabel_title: "Page d'accueil",
	CTMLabel_text: "Marques",
	CTMLabel_title: "La marque communautaire",
	RCDLabel_text: "Dessins et mod&egrave;les",
	RCDLabel_title: "Le dessin et mod&egrave;le communautaire",
	YOULabel_text: "Qualit&eacute; Plus",
	YOULabel_title: "Qualit&eacute; Plus",
	ABOUTLabel_text: "&Agrave; propos de l'OHMI",
	ABOUTLabel_title: "&Agrave; propos de l'OHMI",
	breadcrumb: "Vous &ecirc;tes ici",
	languages_title: "Utilisateurs du clavier: appuyez sur ALT+fl&egrave;che vers le bas pour ouvrir le menu d&eacute;roulant et parcourir les diff&eacute;rentes versions linguistiques, puis appuyez sur  la touche ENTER pour faire votre s&eacute;lection",
	
	// CTM Menu
	CTMTitle: "Marques",
	CTMWhatIs: "Qu'est-ce qu'une marque?",
	CTMWhatIsCommunity: "Qu'est-ce qu'une marque communautaire?",
	CTMExtending: "Extension d'une MC en dehors de l'UE",
	CTMTheCTM: "La marque communautaire",
	CTMInternationalRegistrations: "Enregistrements internationaux d&eacute;signant la CE",
	CTMInternationalMark: "MC et marque internationale",
	CTMPublication: "La publication",
	CTMSearches: "Les recherches",
	CTMOpposition: "L'opposition",
	CTMRegistration: "L'enregistrement",
	CTMInvalidity: "La nullit&eacute; et la d&eacute;ch&eacute;ance",
	CTMFeesPayments: "Les taxes et leur paiement",
	CTMBulletin: "Le Bulletin des marques communautaires",
	CTMNotifications: "Les notifications par voie de publication",
	CTMJudgements: "Les d&eacute;cisions des tribunaux des marques communautaires",
	CTMManual: "Manuel de l'OHMI sur la pratique actuelle en mati&egrave;re de MC",
	
	// RCD Menu
	RCDTitle: "Designs",
	RCDWhatIs: "Qu'est-ce qu'un dessin ou modèle?",
	RCDWhatIsCommunity: "Qu'est-ce qu'un dessin ou modèle communautaire?",
	RCDRegisteredRCD: "TLe dessin ou modèle communautaire",
	RCDInternationalRegistrations: "Les enregistrements internationaux",
	RCDUnregistered: "Le dessin ou modèle communautaire non enregistr&eacute;",
	RCDRegistrationPublication: "L'enregistrement et la publication",
	RCDInvalidity: "La nullit&eacute;",
	RCDFeesPayment: "Les taxes et leur paiement",
	RCDBulletin: "Le Bulletin des dessins ou modèles communautaires",
	RCDNotifications: "Les notifications par voie de publication",
	RCDInvalidityDecisions: "Les d&eacute;cisions de nullit&eacute;/Proc&eacute;dures en cours",
	RCDBoards: "Les d&eacute;cisions des chambres de recours",
	RCDJudgementsCourt: "Les arrêts de la Cour de justice",
	RCDJudgements: "Les d&eacute;cisions des tribunaux des dessins ou modèles communautaires",
	
	// YOU Menu
	YOUTitle: "Qualit&eacute; plus",
	YOUQuality: "Le syst&egrave;me de gestion de la qualit&eacute;",
	YOUService: "La charte des services",
	YOUSatisfaction: "L'enqu&ecirc;te de satisfaction aupr&egrave;s des usagers",
	YOUComplaints: "L'unit&eacute; des r&eacute;clamations",
	YOUCooperationProjects: "Accords de coop&eacute;ration technique avec les offices nationaux",
	YOUNetworks: "Les r&eacute;seaux et les groupes d'usagers",
	YOUOffices: "Les offices nationaux",
	YOUOAMIGroup: "Le groupe d'usagers de l'OHMI",
	YOUEBusinessGroup: "Le groupe d'utilisateurs des outils d'affaires en ligne",
	YOUEuropeanJudges: "Le symposium des juges europ&eacute;ensLe symposium des juges europ&eacute;ens",
	YOUCooperation: "Coop&eacute;ration trilat&eacute;rale avec les &Eacute;tats-Unis et le Japon",
	YOUOHIMNetwork: "OHIM Universities Network",
	YOULinks: "Liens",
	YOUMyPage: "MyPage",
	YOUDatabases: "Les banques de donn&eacute;es",
	YOUSearchCTM: "Recherche d'une marque communautaire",
	YOUSearchRCD: "Recherche d'un dessin ou mod&egrave;le communautaire",
	YOUSearchEuronice: "Recherche d'une classification pour les marques - EURONICE/EUROACE",
	YOUSearchEurolocarno: "Recherche d'une classification pour les dessins ou mod&egrave;les - EUROLOCARNO",
	YOUFindRep: "Recherche d'un repr&eacute;sentant - FindRep",
	YOUEuroclass: "EuroClass",
	YOUFormsFilings: "Les formulaires",
	YOUOnlineFiling: "&Eacute;lectroniques",
	YOUFileCTM: "D&eacute;p&ocirc;t d'une demande de marque communautaire",
	YOUFileRCD: "D&eacute;p&ocirc;t d'une demande de dessin ou mod&egrave;le communautaire",
	YOURenewCTM: "Renouvellement d'une marque communautaire",
	YOURenewRCD: "Renouvellement d'un dessin ou mod&egrave;le communautaire",
	YOUFileOpposition: "D&eacute;p&ocirc;t d'un acte d'opposition",
	YOUDownloadable: "Non &eacute;lectroniques",
	
	// ABOUT Menu
	ABOUTTitle: "À propos de l’OHMI",
	ABOUTContact: "Contactez-nous",
	ABOUTInstitutionalInformation: "Informations institutionnelles",
	ABOUTWelcome: "Le message de bienvenue du pr&eacute;sident",
	ABOUTAdministrative: "Conseil d'administration et comit&eacute; budg&eacute;taire",
	ABOUTFinance: "Les finances",
	ABOUTChart: "L'organigramme",
	ABOUTAppeal: "Les chambres de recours",
	ABOUTEnlargement: "L'&eacute;largissement",
	ABOUTRequesting: "Demande de documents administratifs",
	ABOUTStatistics: "Statistiques",
	ABOUTPublications: "Publications de l'OHMI",
	ABOUTNewsEvents: "Actualit&eacute; et &eacute;v&eacute;nements",
	ABOUTNews: "Actualit&eacute;",
	ABOUTEvents: "&Eacute;v&eacute;nements",
	ABOUTMultimedia: "Multim&eacute;dia",
	ABOUTCorporate: "OHMI - L&rsquo;institution",
	ABOUTEBusiness: "OHMI &ndash; Les affaires en ligne",
	ABOUTCareer: "Offres d'emploi et stages",
	ABOUTProcurement: "Proc&eacute;dures ouvertes en cours",
	ABOUTRunning: "Autres proc&eacute;dures en cours",
	ABOUTOtherRunning: "Other runneng procedures",
	ABOUTClosed: "Proc&eacute;dures termin&eacute;es",
	ABOUTUseful: "Documentation utile et autres informations",
	ABOUTEnvironment: "Environnement",
	
	// Menu FAQ
	FAQ: "FAQ",
	FAQ1: "1. Questions g&eacute;n&eacute;rales",
	FAQ2_CTM: "2. La proc&eacute;dure de demande",
	FAQ2_RCD: "2. Les demandes de dessin ou mod&egrave;le communautaire enregistr&eacute;",
	FAQ3_CTM: "3. Les taxes et leur paiment",
	FAQ3_RCD: "3. Les taxes",
	FAQ4_CTM: "4. La repr&eacute;sentation devant l'Office",
	FAQ4_RCD: "4. La repr&eacute;sentation devant l'Office",
	FAQ5_CTM: "5. La proc&eacute;dure d'enregistrement de la MC",
	FAQ5_RCD: "5. La proc&eacute;dure",
	FAQ6: "6. La recherche",
	FAQ7_CTM: "7. Le registre des MC",
	FAQ7_RCD: "7. Le registre",
	FAQ8_CTM: "8. L'opposition",
	FAQ8_RCD: "8. Le dessin ou mod&egrave;le communautaire non enregistr&eacute;",
	FAQ9_CTM: "9. La proc&eacute;dure de nullit&eacute;/d&eacute;ch&eacute;ance",
	FAQ9_RCD: "9. La nullit&eacute;",
	FAQ10_CTM: "10. Le recours",
	FAQ12_RCD: "10. L'&eacute;largissement",
	FAQ11_CTM: "11. L'&eacute;largissement",
	FAQ11_RCD: "11. Le d&eacute;p&ocirc;t &eacute;lectronique (e-filing)",
	FAQ12_CTM: "12. L'enregistrement des marques internationales",
	FAQ12_RCD: "12. FAQ sur l'arrangement de La Haye",
	FAQ13_CTM: "13.Les affaires en ligne (e-business)",
	FAQ13_RCD: "13. Recours",
	
	// Menu Common
	howToProtection: "Comment obtenir la protection?",
	registrationProcess: "La proc&eacute;dure d'enregistrement",
	filing: "Le d&eacute;p&ocirc;t",
	classification: "Les classifications",
	examination: "L'examen",
	changes: "Les modifications au registre",
	appeal: "Le recours",
	representation: "La repr&eacute;sentation devant l'Office",
	inspection: "L'inspection publique et les copies",
	renewals: "Les renouvellements",
	caselaw: "La jurisprudence",
	legalTexts: "Les textes juridiques",
	decisions: "Les d&eacute;cisions de l'Office",
	judgementsEuropean: "Les arr&ecirc;ts de la Cour de justice",
	regulations: "Les r&egrave;glements et les textes connexes",
	president: "Les d&eacute;cisions et communications du pr&eacute;sident",
	guidelines: "Les directives",
	presidium: "Les d&eacute;cisions du pr&eacute;sidium des chambres de recours",
	treaties: "Les trait&eacute;s internationaux",
	enforcement: "Le respect des droits de PI"

}

// Italiano
var labels_it = {
	// Months
	month1: "Gen",
	month2: "Feb",
	month3: "Mar",
	month4: "Apr",
	month5: "Mag",
	month6: "Giu",
	month7: "Lug",
	month8: "Ago",
	month9: "Set",
	month10: "Ott",
	month11: "Nov",
	month12: "Dic",
	
	// Footer Labels
	legalNotices_text: "Avvisi legali",
	legalNotices_title: "Disclaimer e Copyright",
	dataProtection_text: "Tutela dei dati",
	dataProtection_title: "Dichiarizacione dei tutela dei dati personali",
	compatibility_text: "Compatibilit&agrave;",
	compatibility_title: "Compatibilit&agrave;",
	compatibility_src: "http://oami.europa.eu/ows/rw/pages/compatibility.en.do",
	version: "Version",
	organization: "Ufficio per l'Armonizzazione  nel Mercato Interno (Marchi, Disegni e Modelli)",
	address: "Avenida de Europa 4, E-03008 Alicante, Spagna - Tel: +34 96 513 9400 - e-mail",
	
	// Header Labels
	helpFiles_text: "FAQ",
	helpFiles_title: "Domande frequenti",
	helpFiles_src: "",
	contact_text: "Contatto",
	contact_title: "Contatto",
	siteMap_text: "Mappa del sito",
	siteMap_title: "Mappa del sito",
	links_text: "Links",
	links_title: "Links",
	title_text: "UAMI",
	title_title: "Ufficio per l'Armonizzazione nel Mercato Interno",
	description: "L'Ufficio per la registrazione dei marchi, disegni e modelli dell'Unione europea",
	HOMELabel_text: "Home",
	HOMELabel_title: "Home page",
	CTMLabel_text: "Marchi",
	CTMLabel_title: "Il marchio comunitario",
	RCDLabel_text: "Disegni e modelli",
	RCDLabel_title: "Il disegno o modello comunitario",
	YOULabel_text: "Qualit&agrave; Plus",
	YOULabel_title: "Qualit&agrave; Plus",
	ABOUTLabel_text: "Sull'UAMI",
	ABOUTLabel_title: "Sull'UAMI",
	breadcrumb: "Siete qui",
	languages_title: "Per chi usa la tastiera : premere ALT+freccia verso il basso per aprire il men&ugrave; a tendina per consultare le opzioni linguistiche e poi premere ENTER per eseguire la scelta",
	
	// CTM Menu
	CTMTitle: "Marchi",
	CTMWhatIs: "Che cosa si intende per marchio?",
	CTMWhatIsCommunity: "Che cosa si intende per marchio comunitario?",
	CTMExtending: "Estensione di un MC fuori della UE",
	CTMTheCTM: "Il marchio comunitario",
	CTMInternationalRegistrations: "Registrazioni internazionali che designano la CE",
	CTMInternationalMark: "MC e marchio internazionale",
	CTMPublication: "Pubblicazione",
	CTMSearches: "Ricerche",
	CTMOpposition: "Opposizione",
	CTMRegistration: "Registrazione",
	CTMInvalidity: "Nullit&agrave; e decadenza",
	CTMFeesPayments: "Tasse e modalit&agrave; di pagamento",
	CTMBulletin: "Bollettino dei MC",
	CTMNotifications: "Notificazioni mediante pubblicazione",
	CTMJudgements: "Sentenze dei tribunali dei marchi comunitari",
	CTMManual: "Manuale UAMI sulla prassi attuale dei MC",
	
	// RCD Menu
	RCDTitle: "Disegni e modelli",
	RCDWhatIs: "Che cosa si intende per disegno o modello?",
	RCDWhatIsCommunity: "Che cosa si intende per disegno o modello comunitario?",
	RCDRegisteredRCD: "Il disegno o modello comunitario registrato",
	RCDInternationalRegistrations: "Registrazioni internazionali",
	RCDUnregistered: "Il disegno o modello comunitario non registrato",
	RCDRegistrationPublication: "Registrazione e pubblicazione",
	RCDInvalidity: "Nullità",
	RCDFeesPayment: "Tasse e modalità di pagamento",
	RCDBulletin: "Bollettino dei DCR",
	RCDNotifications: "Notifiche mediante pubblicazione",
	RCDInvalidityDecisions: "Decisioni di nullità/Procedimenti in corso",
	RCDBoards: "Decisioni delle Commissioni di ricorso",
	RCDJudgementsCourt: "Sentenze della Corte di giustizia europea",
	RCDJudgements: "Sentenze dei tribunali dei disegni e modelli comunitari",
	
	// YOU Menu
	YOUTitle: "Qualit&agrave; plus",
	YOUQuality: "Sistema di gestione della qualit&agrave;",
	YOUService: "Carta dei servizi",
	YOUSatisfaction: "Indagine sul grado di soddisfazione degli utenti",
	YOUComplaints: "Unit&agrave; Reclami",
	YOUCooperationProjects: "Accordi di cooperazione tecnica con gli uffici nazionali",
	YOUNetworks: "Network e Gruppi di utenti",
	YOUOffices: "Uffici nazionali",
	YOUOAMIGroup: "Gruppo utenti dell'UAMI",
	YOUEBusinessGroup: "Gruppo utenti dell'e-business",
	YOUEuropeanJudges: "Simposio dei giudici europei",
	YOUCooperation: "Cooperazione trilaterale con USA e Giappone",
	YOUOHIMNetwork: "OHIM Universities Network",
	YOULinks: "Link",
	YOUMyPage: "MyPage",
	YOUDatabases: "Banche dati",
	YOUSearchCTM: "Ricerca di un marchio comunitario",
	YOUSearchRCD: "Ricerca di un disegno o modello comunitario",
	YOUSearchEuronice: "Ricerca di una classificazione dei marchi - EURONICE/EUROACE",
	YOUSearchEurolocarno: "Ricerca di una classificazione dei disegni e modelli - EUROLOCARNO",
	YOUFindRep: "Ricerca di un rappresentante - FindRep",
	YOUEuroclass: "EuroClass",
	YOUFormsFilings: "Moduli",
	YOUOnlineFiling: "Elettronico",
	YOUFileCTM: "Deposito di un marchio comunitario",
	YOUFileRCD: "Deposito di un disegno o modello comunitario",
	YOURenewCTM: "Rinnovo di un marchio comunitario",
	YOURenewRCD: "Rinnovo di un disegno o modello comunitario",
	YOUFileOpposition: "Deposito di un'opposizion",
	YOUDownloadable: "Non elettronico",
	
	// ABOUT Menu
	ABOUTTitle: "Sull'UAMI",
	ABOUTContact: "Come contattarci",
	ABOUTInstitutionalInformation: "Informazioni istituzionali",
	ABOUTWelcome: "Saluto del Presidente",
	ABOUTAdministrative: "Consiglio di amministrazione e Comitato del bilancio",
	ABOUTFinance: "Finanze",
	ABOUTChart: "Organigramma",
	ABOUTAppeal: "Commissioni di ricorso",
	ABOUTEnlargement: "Allargamento",
	ABOUTRequesting: "Richiesta di documenti amministrativi",
	ABOUTStatistics: "Statistiche",
	ABOUTPublications: "Pubblicazioni UAMI",
	ABOUTNewsEvents: "Notizie ed eventi",
	ABOUTNews: "Notizie",
	ABOUTEvents: "Eventi",
	ABOUTMultimedia: "Multimedia",
	ABOUTCorporate: "UAMI corporate",
	ABOUTEBusiness: "UAMI e-Business",
	ABOUTCareer: "Opportunit&agrave; di carriera e tirocini",
	ABOUTProcurement: "Procedure aperte in corso",
	ABOUTRunning: "Running open procedures",
	ABOUTOtherRunning: "Altre procedure in corso",
	ABOUTClosed: "Procedure concluse",
	ABOUTUseful: "Documentazione utile e altre informazioni",
	ABOUTEnvironment: "Ambiente",
	
	// Menu FAQ
	FAQ: "FAQ (domande frequenti)",
	FAQ1: "1. Domande generali",
	FAQ2_CTM: "2. Iter della domanda",
	FAQ2_RCD: "2. Domande di disegno o modello comunitario registrato",
	FAQ3_CTM: "3. Tasse e modalit&agrave; di pagamento",
	FAQ3_RCD: "3. Tasse",
	FAQ4_CTM: "4. Rappresentanza dinanzi all'UAMI",
	FAQ4_RCD: "4. Rappresentanza dinanzi all'Ufficio",
	FAQ5_CTM: "5. La procedura di registrazione del MC",
	FAQ5_RCD: "5. Procedura",
	FAQ6: "6. Ricerche",
	FAQ7_CTM: "7. Il registro dei MC",
	FAQ7_RCD: "7. Registro",
	FAQ8_CTM: "8. Opposizione",
	FAQ8_RCD: "8. Il disegno o modello comunitario non registrato",
	FAQ9_CTM: "9. Procedimento di nullit&agrave;/decadenza",
	FAQ9_RCD: "9. Nullit&agrave;",
	FAQ10_CTM: "10. Ricorso",
	FAQ12_RCD: "10. Allargamento",
	FAQ11_CTM: "11. Allargamento",
	FAQ11_RCD: "11. E-Filing",
	FAQ12_CTM: "12. Registrazione di marchi internazionali",
	FAQ12_RCD: "12. FAQ (domande frequenti) sull'Accordo dell'Aia",
	FAQ13_CTM: "13. E-business",
	FAQ13_RCD: "13. Ricorso",
	
	// Menu Common
	howToProtection: "Come ottenere la protezione",
	registrationProcess: "La procedura di registrazione",
	filing: "Deposito",
	classification: "Classificazioni",
	examination: "Esame",
	changes: "Modificazioni nel registro",
	appeal: "Ricorso",
	representation: "Rappresentanza dinanzi all'Ufficio",
	inspection: "Consultazione di fascicoli e copie",
	renewals: "Rinnovi",
	caselaw: "Giurisprudenza",
	legalTexts: "Testi normativi",
	decisions: "Decisioni dell'Ufficio",
	judgementsEuropean: "Sentenze dei tribunali dei marchi comunitari",
	regulations: "Regolamenti e testi correlati",
	president: "Decisioni e comunicazioni del Presidente",
	guidelines: "Direttive interne",
	presidium: "Decisioni del Presidium delle Commissioni di ricorso",
	treaties: "Trattati internazionali",
	enforcement: "Tutela giurisdizionale dei diritti di PI"

}

var labels = {
	de: labels_de,
	en: labels_en,
	es: labels_es,
	fr: labels_fr,
	it: labels_it,
	
	get: function(lang, idlabel) {
		return this[lang][idlabel];
	}
}
